# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f28656bf8186d918be6eeb072880d549974b37755076a08384a381fdb96f0a780f95692e01664486cea8a999621d634a4d2ddd79b63c68d43fafc8000e9defbe

test:
  secret_key_base: 329b59c666cc96c2296e3bb96d288a0c6072f5ce3c118b5692b33e8dcebb782b0e0ee3c3411da4e9345e33b30050a20712d18d994a140b2f8b6ba6b63e5c8c98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
